controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
      state_publish_rate: 50
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.01
        joint1:
          trajectory: 0.1
          goal: 0.1
        joint2:
          trajectory: 0.1
          goal: 0.1
        joint3:
          trajectory: 0.1
          goal: 0.1
        joint4:
          trajectory: 0.1
          goal: 0.1
        joint5:
          trajectory: 0.1
          goal: 0.1

    # gripper_controller:
    #   type: position_controllers/GripperActionController
    #   joints:
    #     - left_finger_joint
    #     - right_finger_joint
    #   state_publish_rate: 50
    #   constraints:
    #     goal_time: 0.2
    #     left_finger_joint:
    #       trajectory: 0.01
    #       goal: 0.01
    #     right_finger_joint:
    #       trajectory: 0.01
    #       goal: 0.01
