controller_manager:
  ros__parameters:
    update_rate: 50
    arm_and_gripper_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - left_finger_joint
        - right_finger_joint
      constraints:
        goal_time: 1.0
        stopped_velocity_tolerance: 0.01
        joint1:
          trajectory: 0.05
          goal: 0.05
        joint2:
          trajectory: 0.05
          goal: 0.05
        joint3:
          trajectory: 0.05
          goal: 0.05
        joint4:
          trajectory: 0.05
          goal: 0.05
        left_finger_joint:
          trajectory: 0.01
          goal: 0.01
        right_finger_joint:
          trajectory: 0.01
          goal: 0.01
      state_publish_rate: 25
      action_monitor_rate: 10
