version: "3.8"

services:
  rasp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasp
    platform: linux/arm64
    tty: true
    network_mode: host  # Shares the same NAT as the host
    restart: unless-stopped
# eventually add volume