version: "3.8"

services:
  rasp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasp
    platform: linux/arm64 # Delete if not on Raspberry Pi or Apple Silicon MACs
    tty: true
    network_mode: host  # Shares the same NAT as the host
    restart: unless-stopped

    # Enable GUI for Apple Silicon MACs
    # environment:
    #   - DISPLAY=host.docker.internal:0
    #   - QT_X11_NO_MITSHM=1
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix:rw --privileged  # X11 socket for GUI sharing
