<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot_arm">

  <!-- Properties -->
  <xacro:property name="base_link_length" value="0.5"/>
  <xacro:property name="first_link_length" value="0.5"/>
  <xacro:property name="second_link_length" value="0.5"/>
  <xacro:property name="third_link_length" value="0.5"/>
  <xacro:property name="fourth_link_length" value="1.0"/>
  <xacro:property name="gripper_length" value="1.0"/>
  <xacro:property name="link_radius" value="0.05"/>
  
  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>
  
  <!-- Joint 1 -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="first_link"/>
    <origin xyz="0 0 ${base_link_length / 2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
  </joint>
  
  <!-- Arm Link -->
  <link name="first_link">
    <visual>
      <geometry>
        <cylinder length="${first_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

<joint name="joint2" type="revolute">
    <parent link="first_link"/>
    <child link="second_link"/>
    <origin xyz="0 0 ${second_link_length / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
  </joint>


  <link name="second_link">
    <visual>
      <geometry>
        <cylinder length="${second_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

<joint name="joint3" type="revolute">
    <parent link="second_link"/>
    <child link="third_link"/>
    <origin xyz="0 0 ${third_link_length / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
  </joint>

  <link name="third_link">
    <visual>
      <geometry>
        <cylinder length="${third_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

<joint name="joint4" type="revolute">
    <parent link="third_link"/>
    <child link="arm_link"/>
    <origin xyz="0 0 ${base_link_length / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
  </joint>

  <link name="arm_link">
    <visual>
      <geometry>
        <cylinder length="${fourth_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>



  <!-- Gripper Properties -->
  <xacro:property name="gripper_finger_length" value="0.1"/>
  <xacro:property name="gripper_finger_width" value="0.02"/>
  <xacro:property name="gripper_finger_range" value="0.04"/>

  <!-- Gripper Base -->
  <link name="gripper_base">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.02"/>
      </geometry>
      <material name="gray"/>
    </visual>
  </link>

  <joint name="gripper_joint" type="fixed">
    <parent link="arm_link"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 ${fourth_link_length / 2}" rpy="0 0 0"/>
  </joint>

  <!-- Left Gripper Finger -->
  <link name="left_finger">
    <visual>
      <geometry>
        <box size="${gripper_finger_width} ${gripper_finger_length} ${gripper_finger_width}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="left_finger"/>
    <origin xyz="0.05 0 ${gripper_finger_width / 2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="${gripper_finger_range}" effort="10" velocity="0.05"/>
  </joint>

  <!-- Right Gripper Finger -->
  <link name="right_finger">
    <visual>
      <geometry>
        <box size="${gripper_finger_width} ${gripper_finger_length} ${gripper_finger_width}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="right_finger"/>
    <origin xyz="-0.05 0 ${gripper_finger_width / 2}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit lower="0" upper="${gripper_finger_range}" effort="10" velocity="0.05"/>
  </joint>

</robot>
