<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot_arm">

  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
    <robotNamespace>/</robotNamespace>
  </plugin>

  <!-- Properties -->
  <xacro:property name="base_link_length" value="0.5"/>
  <xacro:property name="first_link_length" value="0.5"/>
  <xacro:property name="second_link_length" value="0.5"/>
  <xacro:property name="third_link_length" value="0.5"/>
  <xacro:property name="fourth_link_length" value="1.0"/>
  <xacro:property name="gripper_length" value="1.0"/>
  <xacro:property name="link_radius" value="0.05"/>

  <xacro:macro name="define_materials" params="">
    <material name="blue">
      <color rgba="0.0 0.0 1.0 1.0"/>
    </material>
    <material name="red">
      <color rgba="1.0 0.0 0.0 1.0"/>
    </material>
    <material name="gray">
      <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
  </xacro:macro>

  <xacro:define_materials/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder length="${base_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- First Link -->
  <link name="first_link">
    <visual>
      <geometry>
        <cylinder length="${first_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${first_link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.005" ixy="0.0" ixz="0.0" iyy="0.005" iyz="0.0" izz="0.005"/>
    </inertial>
  </link>

<joint name="joint2" type="revolute">
    <parent link="first_link"/>
    <child link="second_link"/>
    <origin xyz="0 0 ${second_link_length / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
  </joint>


  <link name="second_link">
    <visual>
      <geometry>
        <cylinder length="${second_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${second_link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.005" ixy="0.0" ixz="0.0" iyy="0.005" iyz="0.0" izz="0.005"/>
    </inertial>
  </link>

<joint name="joint3" type="revolute">
    <parent link="second_link"/>
    <child link="third_link"/>
    <origin xyz="0 0 ${third_link_length / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
  </joint>

  <link name="third_link">
    <visual>
      <geometry>
        <cylinder length="${third_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${third_link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.005" ixy="0.0" ixz="0.0" iyy="0.005" iyz="0.0" izz="0.005"/>
    </inertial>
  </link>

<joint name="joint4" type="revolute">
    <parent link="third_link"/>
    <child link="arm_link"/>
    <origin xyz="0 0 ${base_link_length / 2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1"/>
  </joint>

  <link name="arm_link">
    <visual>
      <geometry>
        <cylinder length="${fourth_link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${fourth_link_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.8"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Gripper Link -->
  <link name="gripper">
    <visual>
      <geometry>
        <cylinder length="${gripper_length}" radius="${link_radius}"/>
      </geometry>
      <material name="gray"/>
    </visual>
  </link>

  <joint name="gripper_joint" type="fixed">
    <parent link="arm_link"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 ${fourth_link_length / 2}" rpy="0 0 0"/>
  </joint>

  <!-- Left Gripper Finger -->
  <link name="left_finger">
    <visual>
      <geometry>
        <cylinder length="${gripper_length}" radius="${link_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.002"/>
    </inertial>
  </link>


  <joint name="joint5" type="revolute">
    <parent link="fourth_link"/>
    <child link="gripper"/>
    <origin xyz="0 0 ${fourth_link_length/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10.0" velocity="1.0" lower="-1.57" upper="1.57"/>
  </joint>

</robot>
